# Job to sync repositories using a regexp to filter the tags
- job: sync_yaml
  displayName: Sync Filtered
  pool:
    vmImage: 'ubuntu-18.04'
  strategy:
    matrix:
      Python:
        image: python
        regexp: '^[0-9]+\.[^-]+$'
      GoLang:
        image: golang
        regexp: '\d+-stretch'

  steps:
    - script: ./write-auth.py
      displayName: Create auth
      env:
        DOCKER_TOKEN: $(DOCKER_TOKEN)
        QUAY_TOKEN: $(QUAY_TOKEN)

    - script: ./write-yaml.py
      displayName: Create YAML
      env:
        IMAGE: $(image)
        REGEXP: '$(regexp)'

    - script: >
        docker run --rm -t
        -v $(pwd)/auth.json:/auth.json:ro
        -v $(pwd)/images.yml:/images.yml:ro
        quay.io/containers/skopeo:v1.2.0  # This is actually 1.2.2. The tag is incorrect.
        sync
        --authfile /auth.json
        --src yaml
        --dest docker
        /images.yml
        quay.io/bedrock
      displayName: Image
