schedules:
  - cron: 42 0 * * *
    displayName: Nightly Image Sync
    always: true
    branches:
      include:
        - main

jobs:
  - job: sync
    displayName: Sync
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      match: ''
    strategy:
      matrix:
        Alpine:
          image: alpine
        Ubuntu:
          image: ubuntu
          skip_from: skip/ubuntu.txt

    steps:
      - script: ./sync.py docker.io/$(image) quay.io/bedrock --skip-from "$(skip_from)"
        displayName: Sync
        env:
          DOCKER_TOKEN: $(DOCKER_TOKEN)
          QUAY_TOKEN: $(QUAY_TOKEN)
