schedules:
  - cron: 42 0 * * *
    displayName: Nightly Image Sync
    always: true
    branches:
      include:
        - main

jobs:
  - job: sync
    displayName: Sync
    strategy:
      matrix:
        Alpine:
          image: alpine
        CentOS:
          image: centos
        Fedora:
          image: fedora
        openSUSE:
          image: opensuse/leap
        Ubuntu:
          image: ubuntu

    steps:
      - script: ./write-auth.py
        displayName: Create auth
        env:
          DOCKER_TOKEN: $(DOCKER_TOKEN)
          QUAY_TOKEN: $(QUAY_TOKEN)

      - script: >
          docker run --rm -t
            -v $(pwd)/auth.json:/auth.json:ro
            quay.io/containers/skopeo:1.2.0
            sync
            --authfile /auth.json
            --src docker
            --dest docker
            docker.io/$(image)
            quay.io/bedrock
        displayName: Image
