schedules:
  - cron: 42 0 * * *
    displayName: Nightly Image Sync
    always: true
    branches:
      include:
        - main

jobs:
  - job: sync
    displayName: Sync
    pool:
      vmImage: 'ubuntu-18.04'
    strategy:
      matrix:
        Alpine:
          image: alpine
        CentOS:
          image: centos
        Fedora:
          image: fedora
        Nginx:
          image: nginx
          regex: "^(?!^nginx:1\\.19\\.0-alpine$).*$"  # nginx:1.19.0-alpine fails to sync
        openSUSE:
          image: opensuse/leap
        Ubuntu:
          image: ubuntu

    steps:
      - script: ./write-auth.py
        displayName: Create auth
        env:
          DOCKER_TOKEN: $(DOCKER_TOKEN)
          QUAY_TOKEN: $(QUAY_TOKEN)

      - script: ./write-yaml.py
        displayName: Create yaml

      - script: ./sync.py
        displayName: Image
