schedules:
  - cron: 42 0 * * *
    displayName: Nightly Image Sync
    always: true
    branches:
      include:
        - main

jobs:
  - job: sync
    displayName: Sync
    timeoutInMinutes: 120
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      skip_from: ''
    strategy:
      matrix:
        Alpine:
          image: alpine
          match: ^\d+\.\d+\.\d+$
        Ubuntu:
          image: ubuntu
          match: ^[a-z]+-\d{8}(\.\d+)?$
          skip_from: skip/ubuntu.txt

    steps:
      - script: ./sync.py public.ecr.aws/docker/library/$(image) quay.io/bedrock --new-tags-only --match '$(match)' --skip-from "$(skip_from)"
        displayName: Sync
        env:
          QUAY_TOKEN: $(QUAY_TOKEN)
