schedules:
  - cron: 42 0 * * *
    displayName: Nightly Image Sync
    always: true
    branches:
      include:
        - main

jobs:
  - job: sync
    displayName: Sync
    pool:
      vmImage: 'ubuntu-22.04'
    variables:
      match: ''
    strategy:
      matrix:
        Alpine:
          image: alpine
        CentOS:
          image: centos
        Fedora:
          image: fedora
        Nginx:
          image: nginx
          match: "^(?!^1\\.19\\.0-alpine$).*$"  # nginx:1.19.0-alpine fails to sync
        openSUSE:
          image: opensuse/leap
        Ubuntu:
          image: ubuntu

    steps:
      - script: ./sync.py docker.io/$(image) quay.io/bedrock --match "$(match)"
        displayName: Repo
        env:
          DOCKER_TOKEN: $(DOCKER_TOKEN)
          QUAY_TOKEN: $(QUAY_TOKEN)
